version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13-browsers
        entrypoint: /docker-entrypoint.sh
    resource_class: small
    steps:
      - run: |
          printenv FOO

workflows:
  main:
    jobs:
      - build:
          context:
            - foo-1
            - foo-2
            - foo-3
